import os
import subprocess
import re
from datetime import datetime
from pathlib import Path
from fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP("PDF-to-Markdown-Obsidian")

def post_process_markdown(md_path: Path):
    """
    Chuẩn hóa nội dung Markdown theo chuẩn Obsidian Skill (Internal function).
    """
    with open(md_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Thêm YAML Frontmatter (nếu chưa có)
    if not content.startswith('---'):
        title = md_path.stem.replace('-', ' ').title()
        date_str = datetime.now().strftime('%Y-%m-%d')
        yaml_header = f"---\ntitle: \"{title}\"\ndate: {date_str}\ntags: [converted, pdf, automated]\n---\n\n"
        content = yaml_header + content

    # Tách YAML và Body để tránh làm hỏng Frontmatter
    parts = content.split('---', 2)
    if len(parts) >= 3:
        yaml_part = parts[1]
        body_part = parts[2]
        
        # 1. Xóa Header lặp lại và thay bằng Page Marker
        headers_to_remove = [
            r'HỒ SƠ MỜI THẦU',
            r'PHẦN 1 - CHƯƠNG I',
            r'VIỆN NĂNG LƯỢNG',
            r'MÔ TẢ TÓM TẮT'
        ]
        pattern_header = r'(?:#\s*)?(?:' + '|'.join(headers_to_remove) + r')\s*\n*'
        page_counter = [1]
        def page_replacer(match):
            page_num = page_counter[0]
            marker = f"\n\n%% [Trang {page_num}] %%\n\n"
            page_counter[0] += 1
            return marker

        body_part = re.sub(f"({pattern_header}){{2,}}", page_replacer, body_part)

        # 2. Tự động tạo WikiLink cho các thuật ngữ (idempotent: không lồng nếu đã có link)
        body_part = re.sub(r'(?<!\|)(?<!\[)\bBDL\b(?!\])', r'[[Chương II - Bảng dữ liệu đấu thầu 29.3|BDL]]', body_part)
        body_part = re.sub(r'(?<!\|)(?<!\[)\bCDNT\b(?!\])', r'[[Chương I - Chỉ dẫn nhà thầu 29.3|CDNT]]', body_part)
        body_part = re.sub(r'(?<!\|)(?<!\[)\bHSMT\b(?!\])', r'[[Hồ sơ mời thầu|HSMT]]', body_part)

        # 3. Chuẩn hóa ngày tháng trong phần Body
        def date_replacer(match):
            d, m = match.group(1), match.group(2)
            y = match.group(3) if match.group(3) else "2026"
            if len(y) == 2: y = "20" + y
            return f"{y}-{m.zfill(2)}-{d.zfill(2)}"

        body_part = re.sub(r'\b(\d{1,2})[/-](\d{1,2})(?:[/-](\d{2,4}))?\b', date_replacer, body_part)
        
        # 4. Chuyển đổi thành Obsidian Callouts
        body_part = re.sub(r'▸ \*\* Đầu ra: \*\*', r'> [!success] Đầu ra', body_part)
        body_part = re.sub(r'▸ \*\* Không nên chứa: \*\*', r'> [!warning] Không nên chứa', body_part)
        body_part = re.sub(r'▸ \*\* Lưu ý: \*\*', r'> [!info] Lưu ý', body_part)

        # 5. Highlight tiền tệ
        body_part = re.sub(r'(\d{1,3}(,\d{3}){1,})', r'==\1==', body_part)
        
        content = f"---{yaml_part}---{body_part}"

    # 5. Clean whitespace
    content = re.sub(r'\n{3,}', r'\n\n', content)

    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(content)

@mcp.tool()
def convert_pdf_to_obsidian(pdf_path: str, output_folder: str = None) -> str:
    """
    Convert a PDF file to a clean, Obsidian-ready Markdown file.
    
    Args:
        pdf_path: Absolute path to the source PDF file.
        output_folder: Optional absolute path to the output folder. If not provided, 
                       it will use the 'tests' folder in the skill directory.
    """
    pdfmd_exe = r"C:\Users\HP\AppData\Roaming\Python\Python311\Scripts\pdfmd.exe"
    default_output = r"D:\DATA\MEMORY\Second memory\10.Inbox\12.Random Idea\SKILL_VANPHONG_VIETNAM\tests"
    
    source_pdf = Path(pdf_path)
    out_dir = Path(output_folder) if output_folder else Path(default_output)
    
    if not source_pdf.exists():
        return f"Error: PDF file not found at {pdf_path}"
    
    if not out_dir.exists():
        out_dir.mkdir(parents=True)

    try:
        # Step 1: Run pdfmd
        subprocess.run(
            [pdfmd_exe, str(source_pdf), "-o", str(out_dir)],
            capture_output=True,
            text=True,
            check=True
        )
        
        # Step 2: Post-process
        md_file = out_dir / (source_pdf.stem + ".md")
        if md_file.exists():
            post_process_markdown(md_file)
            return f"Success! Converted '{source_pdf.name}' to '{md_file.name}' in {out_dir}"
        else:
            return "Error: Markdown file was not generated by pdfmd."
            
    except subprocess.CalledProcessError as e:
        return f"Process Error: {e.stderr}"
    except Exception as e:
        return f"Unexpected Error: {str(e)}"

if __name__ == "__main__":
    mcp.run()
